### ISSUE TITLE
Peer Review #1

### ISSUE THREAD

**Issue by apang00** [varygx/AnimeAnalysis#1]
ReadMe:
- The title could be a little more descriptive, similarly the overview could be more descriptive as well
- For the Downloading data section, it can be moved into the scripts section

Others:
- Great sketches, they look like a good starting point for the project

paper.pdf:
- the title and subtitle are a little confusing, could be a little bit more descriptive and relevant to the topic
- Use "Abstract" label for abstract, great abstract though, very informative
- For the first table, I think the clean data kept too many columns. If all the columns are necessary, I recommend using two separate tables where the first one takes the first 5 columns of the file and the next one takes the latter 5. The table is a little squished and hard to read
- The graphs and description for the graphs are very well done. The graphs are insightful and clean, the descriptions give a good analysis regarding what the graph is plotting
- Overall, the data description, the models descriptions are all solid and done well. 
- There are a few tables that came at the end, I think those can  be integrated into your actual data, model, and results sections
Overal, very well done

download data script:
- Not too sure what this does, maybe a description would be good:

> Sys.unsetenv("BEARER_TOKEN")
> load_dot_env()
> BEARER_TOKEN <- Sys.getenv("BEARER_TOKEN")

- everything else looks good, but I feel some docstrings would help with navigation
- the data cleaning and data testing look good, similar comment as before though. Try to add some docstrings for direction
- The model script is good as well

Overall, great work. a little bit of fine tuning with some wording and organization would make the whole project spectacular

**Comment by varygx** [comment]
Thanks for your feedback! I added more documentation to my scripts and adjusted the tables.
