### ISSUE TITLE
Peer Review By Fatimah 

### ISSUE THREAD

**Issue by fatimahsy** [varygx/AnimeAnalysis#2]
## Overall

- The readme is lacking a bit of information. Adding more information about what you di in your paper in the overview section would be nice. 
- tests are very descriptive and comprehensive. 

## Paper 

- I like how the subtitle tells us exactly what you found. 
- The heading for introduction contains the word 'longer', this is probably for your personal preference but don't forget to take it out when you're done. 
- I like the way you take the time to describe new words or concepts in your introduction, it makes following along easier. 
- Your model justification' section is a bit too short. Adding more information to explain why you chose this specific model and some literature to back it up. 
- For your 'results' section, it might be beneficial to include more forms of summary statistics To make sure the reader knows exactly what tour results are. 
- I like how you included an 'applications' subsection, this is very creative and efficient. 
- For key finding 3 in your discussion section, you seem to have a mistake (indicatowwwwr).Don't forget to fix that. 

Overall, very creative topic!!

**Comment by varygx** [comment]
Thanks for catching that spelling mistake. I updated the README and will look at adding more to the model justification.
